Repository InterviewExplorer/InterviewExplorer_front, pull requests merged in 2024-09, with the labels that each got.

#16 Feature/async axios
  src/pages/Interview_technical.js
Labels: Priority: Medium

#19 Feature/feedback consolidator
  src/pages/Interview_technical.js
  src/pages/VideoRecorder.js
  src/util/FeedbackConsolidator.js
Labels: Type: Feature, Priority: High

#24 Feature/feedback consolidator
  package-lock.json
  package.json
  src/pages/Interview_technical.js
  src/pages/VideoRecorder.js
  src/util/FeedbackConsolidator.js
Labels: Type: Feature, Priority: High

#29 캠 + 마이크 가이드 추가
  src/App.js
  src/pages/ MicTest.js
  src/pages/CamTest.js
  src/pages/GetInfo.js
  src/pages/Guide.js
Labels: Priority: Low

#30 Feature/feedback consolidator
  src/pages/Interview.js
  src/pages/Interview_technical.js
  src/pages/Report.js
  src/pages/VideoRecorder.js
  src/util/FeedbackConsolidator.js
Labels: Type: Feature, Priority: High

#31 피드백 리스트 값 넘어오기 확인
  src/pages/Interview.js
  src/pages/Report.js
  src/pages/VideoRecorder.js
Labels: Type: Feature, Priority: High

#35 Feature/openai basic
  src/App.js
  src/pages/GetInfo_uh.js
  src/pages/Guide_uh.js
  src/pages/Interview_uh.js
  src/pages/Main.js
  src/pages/VideoRecorder.js
Labels: Type: Feature, Priority: Medium

#36 꼬리질문 생성 로직 변경
  src/pages/FollowUp2.js
Labels: Priority: High

#40 resumeConnect
  src/pages/Guide.js
  src/v2/GetInfo2.js
  src/v2/Interview2.js
Labels: Priority: High
